### ISSUE TITLE
Issues in generated AndroidManifest.xml

### ISSUE THREAD

**Issue by calexo** [takimafr/androidkickstartr#6]
Testing using ABS.
1. The theme value is not set. So, Android SDK complains about it, saying it must use a Sherlock Theme.
2. Activity name is wrong in that file: my activity name has been added an undersore _
Thanks a lot !

**Comment by a-thomas** [comment]
Hi Calexo, 

Thanks for the issue.

The `_` is given by [AndroidAnnotations](https://github.com/excilys/androidannotations), it's well explained [here](https://github.com/excilys/androidannotations/wiki/HowItWorks).

Anyway, theses problems should be resolved since my [last commit](https://github.com/a-thomas/androidkickstartr/commit/9a6991bd75e0c72da3f240dc5de1d02dc07de595).

I pushed and deployed theses changes. Could you try to generate a project again and confirm that it fixed ?

**Comment by a-thomas** [comment]
It's very weird. 

Generating a project with ABS required that you follow exactly these steps : 

1) For ABS : **Create** an "Android project from existing Code" and set the path to the library dir.
2) For your app: **Import** the your project as a **General** project in Eclipse (_Import_ > _General_ > _Existings project into workspace_) and not as an "Existing Android Code into workspace". Importing your project as an "Existing Android Code into workspace" results to the error that you mention above.

If it's what you did, could you tell me the libs that you chose, the parameters of your app and all the versions of your environment (Eclipse, ADT etc...) ?

Thanks @calexo

**Comment by a-thomas** [comment]
> 1. The theme value is not set. So, Android SDK complains about it, saying it must use a Sherlock Theme.

From now, the theme is set in the AndroidManifest (306ed2d02017b3df4ce8207e67269f961b39d958).

> 1. Activity name is wrong in that file: my activity name has been added an undersore _

See 2) from my last comment.
