### ISSUE TITLE
Add support of Android Studio

### ISSUE THREAD

**Issue by tagrudev** [takimafr/androidkickstartr#94]
It would be great to add support for android studio :)

**Comment by a-thomas** [comment]
It should work choosing "No-Eclipse" project as option.

I'm sure that it works with a Maven project. I'm slightly less sure about non-maven project.

**Comment by kenyee** [comment]
You don't really need support for Android Studio.  The Eclipse Android plugin does this for you if you do a file/export, it will generate a build.gradle for Android Studio.
Going the other way is a lot harder because the Eclipse Android plugin wants your app to be at the top level of your project instead of down in /src/main...
